name: weather_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  http: ^0.12.0+2
  provider: ^3.0.0+1
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: FredokaOne
      fonts:
      - asset: assets/fonts/FredokaOne-Regular.ttf
    - family: Noir
      fonts:
      - asset: assets/fonts/Noir_regular.otf

  assets:
    - assets/images/background.png
    - assets/images/clear_night_city.gif
    - assets/images/clear_night_mountain.gif
    - assets/images/clear_night_ocean.gif
    - assets/images/rainy_day_city.gif
    - assets/images/rainy_day_mountain.gif
    - assets/images/rainy_day_ocean.gif
    - assets/images/rainy_night_lighthouse.gif
    - assets/images/snowy_day_city.gif
    - assets/images/snowy_day_mountain.gif
    - assets/images/sunny_afternoon_city.gif
    - assets/images/sunny_afternoon_mountain.gif
    - assets/images/sunny_afternoon_ocean.gif
    - assets/images/sunny_day_city.gif
    - assets/images/sunny_day_mountain.gif
